# Generated by Django 4.2.16 on 2025-01-17 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dosen",
            fields=[
                ("id_dosen", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=100)),
                ("nip", models.CharField(max_length=20, unique=True)),
                ("departemen", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="JadwalKuliah",
            fields=[
                ("id_jadwal", models.AutoField(primary_key=True, serialize=False)),
                ("hari", models.CharField(max_length=10)),
                ("jam_mulai", models.TimeField()),
                ("jam_selesai", models.TimeField()),
                ("ruangan", models.CharField(max_length=50)),
                (
                    "dosen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.dosen"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mahasiswa",
            fields=[
                ("id_mahasiswa", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=100)),
                ("nim", models.CharField(max_length=20, unique=True)),
                ("program_studi", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MataKuliah",
            fields=[
                ("id_mata_kuliah", models.AutoField(primary_key=True, serialize=False)),
                ("nama_mata_kuliah", models.CharField(max_length=100)),
                ("sks", models.IntegerField()),
                ("semester", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Presensi",
            fields=[
                ("id_presensi", models.AutoField(primary_key=True, serialize=False)),
                ("tanggal", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Hadir", "Hadir"),
                            ("Tidak Hadir", "Tidak Hadir"),
                            ("Izin", "Izin"),
                            ("Sakit", "Sakit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "jadwal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.jadwalkuliah",
                    ),
                ),
                (
                    "mahasiswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.mahasiswa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kelas",
            fields=[
                ("id_kelas", models.AutoField(primary_key=True, serialize=False)),
                ("tahun_akademik", models.CharField(max_length=9)),
                ("semester", models.CharField(max_length=10)),
                (
                    "dosen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.dosen"
                    ),
                ),
                (
                    "mata_kuliah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.matakuliah",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jadwalkuliah",
            name="mata_kuliah",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.matakuliah"
            ),
        ),
    ]
